/*
--INSERT INTO LANGUAGE (LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE) VALUES (1, 'Swedish', 'sv');
--INSERT INTO LANGUAGE(LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE) VALUES(2, 'Latin', 'la');
--INSERT INTO LANGUAGE(LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE) VALUES(3, 'Finnish', 'fi');
--INSERT INTO LANGUAGE(LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE) VALUES(4, 'German', 'de');
--INSERT INTO LANGUAGE(LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE) VALUES(5, 'English', 'en');

--INSERT INTO PART_OF_MAP_TYPE(PART_OF_MAP_TYPE_ID, PART_OF_MAP_TYPE_NAME) VALUES(1, 'Rubrik');
--INSERT INTO PART_OF_MAP_TYPE(PART_OF_MAP_TYPE_ID, PART_OF_MAP_TYPE_NAME) VALUES(2, 'Kartkroppen');
--INSERT INTO PART_OF_MAP_TYPE(PART_OF_MAP_TYPE_ID, PART_OF_MAP_TYPE_NAME) VALUES(3, 'Gränsmarkering');
--INSERT INTO PART_OF_MAP_TYPE(PART_OF_MAP_TYPE_ID, PART_OF_MAP_TYPE_NAME) VALUES(4, 'Utanför kartkroppen');
*/